<?php

  /* MAKE SURE NONE OF MY FUNCTIONS CONFLICT WITH MY OTHER MODULE. */

function tuition_tool_forms_menu(){
  $menu_items = array();

  $menu_items['admin/content/tuition_tool_forms'] = array(
       'title' => 'Tuition Tool Forms',
       'description' => 'Landing Page for the Forms',
       'page callback' => 'drupal_get_form',
       'page arguments' => array('tuition_tool_forms_landing'),
       'access arguments' => array('access default landing'),
							  );

  $menu_items['admin/content/tuition_tool_forms/american_forms'] = array(
       'title' => 'American Studies Forms',
       'description' => 'Generate the American Studies TA/GA Appointment Form',
       'page callback' => 'drupal_get_form',
       'page arguments' => array('tuition_tool_forms_generating_form'),
       'access arguments' => array('access american defaults'),
							  );
  $menu_items['admin/content/tuition_tool_forms/bio_forms'] = array(
       'title' => 'Biology Forms',
       'description' => 'Generate the Biology TA/GA Appointment Form',
       'page callback' => 'drupal_get_form',
       'page arguments' => array('tuition_tool_forms_generating_form'),
       'access arguments' => array('access bio defaults'),
							  );
    $menu_items['admin/content/tuition_tool_forms/chemistry_forms'] = array(
       'title' => 'Chemistry Forms',
       'description' => 'Generate the Chemistry TA/GA Appointment Form',
       'page callback' => 'drupal_get_form',
       'page arguments' => array('tuition_tool_forms_generating_form'),
       'access arguments' => array('access chem defaults'),
							  );
    //DO I NEED A FORM FOR THE 'COLLEGE' AID TYPE?
    $menu_items['admin/content/tuition_tool_forms/ees_forms'] = array(
       'title' => 'EES Forms',
       'description' => 'Generate the EES TA/GA Appointment Form',
       'page callback' => 'drupal_get_form',
       'page arguments' => array('tuition_tool_forms_generating_form'),
       'access arguments' => array('access ees defaults'),
							  );
  $menu_items['admin/content/tuition_tool_forms/epd_forms'] = array(
       'title' => 'EPD Forms',
       'description' => 'Generate the EPD TA/GA Appointment Form',
       'page callback' => 'drupal_get_form',
       'page arguments' => array('tuition_tool_forms_generating_form'),
       'access arguments' => array('access epd defaults'),
							  );
    $menu_items['admin/content/tuition_tool_forms/english_forms'] = array(
       'title' => 'English Forms',
       'description' => 'Generate the English TA/GA Appointment Form',
       'page callback' => 'drupal_get_form',
       'page arguments' => array('tuition_tool_forms_generating_form'),
       'access arguments' => array('access english defaults'),
							  );
  $menu_items['admin/content/tuition_tool_forms/history_forms'] = array(
       'title' => 'History Forms',
       'description' => 'Generate the History TA/GA Appointment Form',
       'page callback' => 'drupal_get_form',
       'page arguments' => array('tuition_tool_forms_generating_form'),
       'access arguments' => array('access history defaults'),
							  );
  $menu_items['admin/content/tuition_tool_forms/math_forms'] = array(
       'title' => 'Math Forms',
       'description' => 'Generate the Math TA/GA Appointment Form',
       'page callback' => 'drupal_get_form',
       'page arguments' => array('tuition_tool_forms_generating_form'),
       'access arguments' => array('access math defaults'),
							  );
  //DO I NEED THE MISCELLANEOUS AID TYPE?
    $menu_items['admin/content/tuition_tool_forms/physics_forms'] = array(
       'title' => 'Physics Forms',
       'description' => 'Generate the Physics TA/GA Appointment Form',
       'page callback' => 'drupal_get_form',
       'page arguments' => array('tuition_tool_forms_generating_form'),
       'access arguments' => array('access physics defaults'),
							  );
    $menu_items['admin/content/tuition_tool_forms/polisci_forms'] = array(
       'title' => 'Political Science Forms',
       'description' => 'Generate the Political Science TA/GA Appointment Form',
       'page callback' => 'drupal_get_form',
       'page arguments' => array('tuition_tool_forms_generating_form'),
       'access arguments' => array('access polisci defaults'),
							  );
  $menu_items['admin/content/tuition_tool_forms/psych_forms'] = array(
       'title' => 'Psychology Forms',
       'description' => 'Generate the Psychology TA/GA Appointment Form',
       'page callback' => 'drupal_get_form',
       'page arguments' => array('tuition_tool_forms_generating_form'),
       'access arguments' => array('access psych defaults'),
							  );
  $menu_items['admin/content/tuition_tool_forms/socanth_forms'] = array(
       'title' => 'SocAnthro Forms',
       'description' => 'Generate the Sociology/Anthropology TA/GA Appointment Form',
       'page callback' => 'drupal_get_form',
       'page arguments' => array('tuition_tool_forms_generating_form'),
       'access arguments' => array('access socanth defaults'),
							  );
  return $menu_items;
  }


function get_years_for_forms(){
  //This function just generates all of the available academic years
  $years = array();
  
  $ent_query = new EntityFieldQuery();
  //new entity query to get the years
  $ent_query->entityCondition('entity_type','taxonomy_term')
    ->entityCondition('bundle','academic_year');

  $match_ents = $ent_query->execute(); //execute the query
  
  foreach($match_ents['taxonomy_term'] as $myent){
    $match_ids[] = $myent->tid; //make a list of matching term ids
  }
  $load_years = entity_load('taxonomy_term',$match_ids); //load the objects into an array
  
  foreach($load_years as $curyear){
    $years[$curyear->tid] = $curyear->name; //make an array with a list of year name and taxonomy term id
  }

  arsort($years);
  return $years;
}

function get_terms_for_forms($year){
  //need to use a query function to get terms for the current year.

  $terms = array();

  $ent_query = new EntityFieldQuery;

  $ent_query->entityCondition('entity_type','taxonomy_term')
    ->entityCondition('bundle','termcodes')
    ->fieldCondition('field_academic_year','tid',$year,'=');
  
  $match_ents = $ent_query->execute();

  foreach($match_ents['taxonomy_term'] as $myent){
    $match_ids[] = $myent->tid;
  }
  $load_terms = entity_load('taxonomy_term',$match_ids);

  uasort($load_terms,'sort_terms_by_code');  //This function is in the tuition tool module
  foreach($load_terms as $curterm){
    $terms[$curterm->tid] = $curterm->name;
  }

  return $terms;
}

function get_dept_ents_from_url($form_url){
  //only used in get_students

  $dept_forms_array = explode('/',$form_url);
  $dept = explode('_forms',$dept_forms_array[4]);

  $title_map = array('american' => array('american_aid_entry','american_aid_type'),
		     'bio' => array('bio_aid_entry','bio_aid_type'),
		     'chemistry' => array('chem_aid_entry','chem_aid_type'),
		     'ees' => array('ees_aid_entry','ees_aid_type'),
		     'english' => array('english_aid_entry','english_aid_type'),
		     'epd' => array('epd_aid_entry','epd_aid_type'),
		     'history' => array('history_aid_entry','history_aid_type'),
		     'math' => array('math_aid_entry','math_aid_type'),
		     'physics' => array('physics_aid_entry','physics_aid_type'),
		     'polisci' => array('polisci_aid_entry','polisci_aid_type'),
		     'psych' => array('psych_aid_entry','psych_aid_type'),
		     'socanth' => array('psych_aid_entry','psych_aid_type'),
		     );
  
  if(isset($title_map[$dept[0]])){
    return $title_map[$dept[0]];
  }
  else{
    return array('misc_aid_entry','misc_aid_type');
  }

}

function get_dept_title_from_url($form_url){
  $dept_forms_array = explode('/',$form_url);
  $dept = explode('_forms',$dept_forms_array[4]);

  $title_map = array('american' => 'American Studies',
		     'bio' => 'Biological Sciences',
		     'chemistry' => 'Chemistry',
		     'ees' => 'Earth and Environmental Sciences',
		     'english' => 'English',
		     'epd' => 'Environmental Policy',
		     'history' => 'History',
		     'math' => 'Mathematics',
		     'physics' => 'Physics',
		     'polisci' => 'Political Science',
		     'psych' => 'Psychology',
		     'socanth' => 'Sociology',
		     );
  
  if(isset($title_map[$dept[0]])){
    return $title_map[$dept[0]];
  }
  else{
    return '';
  }

}
function get_students($term,$form_url,$aid_nid,$stipendtuition,$sortorder){
  //function get_students($term,$form_url,$aid_nid,$stipendtuition){
  $dept_ents = get_dept_ents_from_url($form_url);
  $entry=$dept_ents[0];
  $aid=$dept_ents[1];

  $students = array();

  $sort_field = array(
		      'last' => array(0=>'field_student_last_name', 1=> 'value'),
		      'first' => array(0=>'field_student_first_name', 1=> 'value'),
		      'account' => array(0=>'field_account_number', 1=> 'value'),
		      'effort' => array(0=>'field_effort', 1=> 'value'),
		      'periods' => array(0=>'field_pay_periods', 1=> 'value'),
		      'stipend' => array(0=>'field_stipend', 1=> 'value'),
		      'credits' => array(0=>'field_credits', 1=> 'value'),
		      'tuition' => array(0=>'field_tuition', 1=> 'value'),
		      'start' => array(0=>'field_aid_date', 1=> 'value'),
		      'end' => array(0=>'field_aid_date', 1=> 'value2'),
		      );

  //NOW DO A FIELD QUERY ON THE AID ENTRY AND RETURN A LIST OF RELEVANT VALUES INDEXED BY THE NID
  $entry_query = new EntityFieldQuery;
  $entry_query-> entityCondition('entity_type','node')
    ->entityCondition('bundle',$entry)
    ->propertyCondition('status',NODE_PUBLISHED)
    ->fieldCondition('field_term','tid',$term,'=')
    ->fieldCondition('field_aid_type','target_id',$aid_nid,'=')
    ->fieldCondition('field_account_number','value',0,'>');//make sure the account number is filled in. required for all entries into these forms
  
  if($stipendtuition == 1){
    $entry_query->fieldCondition('field_tuition','value',0,'>')
      ->fieldCondition('field_credits','value',0,'>');
  }
  else{
    //STIPEND IS THIS REQUIRED? IT FILTERS OUT STIPEND < 0
    $entry_query->fieldCondition('field_stipend','value',0,'>');
  }

  //Here is where the field order by stuff is going to go, start with last name only
  $entry_query->fieldOrderBy($sort_field[$sortorder][0],$sort_field[$sortorder][1],'ASC');

  
  $match_entries = $entry_query->execute();

  $load_entries = entity_load('node',array_keys($match_entries['node']));

  foreach($load_entries as $nid => $curentry){
    $effort = !empty($curentry->field_effort['und'][0]['value']) ? $curentry->field_effort['und'][0]['value'] : 0;
    $periods = !empty($curentry->field_pay_periods['und'][0]['value']) ? $curentry->field_pay_periods['und'][0]['value'] : 0;
    $stipend = !empty($curentry->field_stipend['und'][0]['value']) ? '$'.number_format($curentry->field_stipend['und'][0]['value'],2,'.',',') : 0;
    $credits = !empty($curentry->field_credits['und'][0]['value']) ? $curentry->field_credits['und'][0]['value'] : 0;
    $tuition = !empty($curentry->field_tuition['und'][0]['value']) ? '$'.number_format($curentry->field_tuition['und'][0]['value'],2,'.',',') : 0;
    //make sure the start and end date aren't empty and display zeros if they are empty
    if(empty($curentry->field_aid_date['und'][0]['value'])){
      $start_date = '00-00-0000';
    }
    else{
      $start = new DateTime($curentry->field_aid_date['und'][0]['value']);
      $start_date = $start->format('m-d-Y');
    }
    if(empty($curentry->field_aid_date['und'][0]['value2'])){
      $end_date = '00-00-0000';
    }
    else{
      $end = new DateTime($curentry->field_aid_date['und'][0]['value2']);
      $end_date = $end->format('m-d-Y');
    }
    
    $students[$curentry->nid] = array(
      'last' => '<a href="/node/'.$nid.'">'.$curentry->field_student_last_name['und'][0]['value'].'</a>',
      'first' => $curentry->field_student_first_name['und'][0]['value'],
      'account' => $curentry->field_account_number['und'][0]['value'],
      //below here the values aren't required, for now.      
      'stipend' => $stipend,
      'effort' => $effort,
      'periods' => $periods,
      'credits' => $credits,
      'tuition' => $tuition,
      'start' => $start_date,
      'end' => $end_date,
				      );
  }

  return $students;
}

function get_aid_types_for_form($year, $form_url){
  $dept_ents = get_dept_ents_from_url($form_url);
  $aid_bundle = $dept_ents[1];

  $aid_list = array();

  $aid_query = new EntityFieldQuery;
  $aid_query-> entityCondition('entity_type','node')
    ->entityCondition('bundle',$aid_bundle)
    ->propertyCondition('status',NODE_PUBLISHED)
    ->fieldCondition('field_term_year','tid',$year,'=');

  $match_aid_query = $aid_query->execute();
  
  $loadedents= entity_load('node',array_keys($match_aid_query['node']));
  
  foreach($loadedents as $curaid){
    $aid_list[$curaid->nid] = $curaid->title;
  }
    
  return $aid_list;
}


function tuition_tool_forms_landing($form, &$form_state){
  $form['landing_markup'] = array(
				  '#markup'=>'<h1>This is simply a landing page for the other form generating pages to branch out from.  This page is purposefully blank</h1>');

  //return system_settings_form($form);
  return $form;
}


function tuition_tool_forms_generating_form($form, &$form_state){
  $default_year = variable_get('default_year');

  $formyears = get_years_for_forms(); //This will stay, some of the other variables will change.

  $blank_header = array('meh'=>'PLEASE SELECT A TERM AND AID TYPE TO GENERATE A LIST OF STUDENTS FROM WHICH YOU CAN GENERATE YOUR FORM');
  $blank_table = array();

  $header = array(
		  'last' => 'Last Name',
		  'first' => 'First Name',
		  'account' => 'Account',
		  'effort' => 'Effort',
		  'periods' => 'Pay Periods',
		  'stipend' => 'Stipend',
		  'credits' => 'Credits',
		  'tuition' => 'Tuition',
		  'start' => 'Start Date',
		  'end' => 'End Date',
		  );


  $form['set_ta_ga_actions'] = array(
	  '#type' => 'actions',
	  '#weight' => -10,
					  );
  
  $form['set_ta_ga_actions']['set_form_year'] = array(
	'#type' => 'select',						
	'#title' => t('FIRST: Please select the year from which to generate this form'),
	'#options' => $formyears,
	'#required' => TRUE,
	'#default_value' => variable_get('default_year'), //THIS IS one reason WHY TUITION TOOL MODULE IS REQUIRED.
	'#ajax' => array(
			 'callback' => 'alter_term_choices',
			 'wrapper' => 'term-choices-list',
			 'method' => 'replace',
			 'effect' => 'fade'),	
						      );
  
  $form['term_select_field_set'] = array(
	 '#type' => 'fieldset',
	 '#prefix' => '<div id="term-choices-list">',
	 '#suffix' => '</div>',
	 '#weight' => -9,
					 );

  $form['term_select_field_set']['select_term'] = array(
	'#type' => 'select',
	'#weight' => -5,
	'#title' => t('SECOND: Please select Term from which to generate forms'),
	'#required' => TRUE,
	'#options' => !empty($form_state['values']['set_form_year']) ? get_terms_for_forms($form_state['values']['set_form_year']) : get_terms_for_forms($default_year),
	'#ajax' => array(
			 'callback' => 'get_aid_type_list',
			 'wrapper' => 'select-aid-type-list',
			 'method' => 'replace',
			 'effect' => 'fade'),
							);
  $form['term_select_field_set']['select_aid_type'] = array(
	'#type' => 'fieldset',
	'#weight' => -3,
	'#prefix' => '<div id="select-aid-type-list">',
	'#suffix' => '</div>',
							    );
  $form['term_select_field_set']['select_aid_type']['aid_type_select_list'] = array(
	'#type' => 'select',
	'#weight' => -4,
	'#title' => t('THIRD: Please Select the aid types from which to generate your form'),
	//'#multiple' => TRUE,
	'#required' => TRUE,
	'#options' => !empty($form_state['values']['set_form_year']) ? get_aid_types_for_form($form_state['values']['set_form_year'], $form_state['complete form']['#action']) : array('empty-list'),
	'#ajax' => array(
			 'callback' => 'create_student_choices',
			 'wrapper' => 'select-students-table',
			 'method' => 'replace',
			 'effect' => 'fade'),
											      );
  $form['term_select_field_set']['select_aid_type']['tuition_or_stipend'] = array(
        '#type' => 'radios',
	'#title' => t('FOURTH: Choose which Field, Tuition or Stipend, Students must have a value for to be in the list'),
	'#weight' => -2,
	'#options' => array(0 => t('Stipend > 0'), 1 => t('Tuition > 0')),
	'#default_value' => 0,
	'#description' => t('Please choose if the list of students should be populated with students with stipend > 0 (for TA/GA Appointment list or Payroll assignment form) or Tuition > 0 (for Tuition Award form)'),
	'#ajax' => array(
			 'callback' => 'create_student_choices',
			 'wrapper' => 'select-students-table',
			 'method' => 'replace',
			 'effect' => 'fade'),
							       );
  $form['term_select_field_set']['select_aid_type']['column_sort'] = array(
        '#type' => 'radios',
	'#title' => t('OPTIONALLY: Choose a column to sort the student entries by'),
	'#weight' => -1,
	'#options' => $header,
	'#default_value' => 'last',
	'#description' => t('You can choose a different column to sort the student list by, default is last name. NOTE: Sorting by a column with an empty value will remove those entries!'),
	'#ajax' => array(
			 'callback' => 'create_student_choices',
			 'wrapper' => 'select-students-table',
			 'method' => 'replace',
			 'effect' => 'fade'),
							       );
  $form['term_select_field_set']['select_aid_type']['select_ta_ga_students'] = array(
	'#type' => 'actions',
	'#weight' => 0,
	'#prefix' => '<div id="select-students-table">',
	'#suffix' => '</div>',
					 );
  $form['term_select_field_set']['select_aid_type']['select_ta_ga_students']['choose_students_table'] = array(
	'#type' => 'tableselect',
	'#header' => !empty($form_state['values']['select_term']) ? $header : $blank_header,
	'#options' =>(!empty($form_state['values']['select_term']) && !empty($form_state['values']['aid_type_select_list'])) ? 
	get_students($form_state['values']['select_term'],$form_state['complete form']['#action'],$form_state['values']['aid_type_select_list'],$form_state['values']['tuition_or_stipend'],$form_state['values']['column_sort']) : $blank_table,
	'#weight' => 10,
								  );
  $form['term_select_field_set']['dev_notes'] = array(
        '#type' => 'markup',
	'#markup' => '',
	'#weight' => -10,
			     );
  /*FORM GENERATING BUTTONS!*/
  $form['form_building_buttons'] = array(
	'#title' => 'Form Generating buttons',
	'#type' => 'fieldset',
	'#weight' => -5,
					 );
  $form['form_building_buttons']['build_appointment_list'] = array(
        '#type' => 'submit',
	'#value' => 'Build TA/GA Appointment List',
	'#submit' => array('tuition_tool_forms_ta_ga_submit'),
	'#weight' => -5,
								   );
  $form['form_building_buttons']['generate_payroll_asignment_form'] = array(
        '#type' => 'submit',
	'#value' => 'Generate Payroll Assignment Forms',
	'#submit' => array('tuition_tool_forms_payroll_assignment'),
	'#weight' => -4,
								   );
  $form['form_building_buttons']['generate_tuition_award_form'] = array(
	'#type' => 'submit',
	'#value' => 'Generate Tuition Award Forms',
	'#submit' => array('tuition_tool_forms_tuition_award'),
	'#weight' => -3,
									);

  //This space below here generates the TA/GA form. 
  if($form_state['submitted'] == TRUE){
    if(!empty($form_state['values']['choose_students_table']) && $form_state['values']['tuition_or_stipend'] == 0){
      $students_selected = FALSE;//This variable and following for loop makes sure this doesn't activate unless at least 1 student is selected
      foreach($form_state['values']['choose_students_table'] as $value){
	if($value > 0){
	  $students_selected = TRUE;
	  break;
	}
      }
      if($students_selected){    
	drupal_add_css(drupal_get_path('module','tuition_tool_forms').'/tuition_tool_forms.css');
	//removes the form stuff to only display the Appointment List
	unset($form['set_ta_ga_actions']);
	unset($form['term_select_field_set']);
	//unset($form['select_ta_ga_students']);
	//unset($form['build_appointment_list']);
	unset($form['form_building_buttons']);
	unset($form['dev_notes']);
	
	$student_list = array();
	
	$term_id = $form_state['values']['select_term'];
	
	foreach( $form_state['values']['choose_students_table'] as $stud_nid){
	  if($stud_nid > 0){
	    $student_list[] = $stud_nid;
	  }
	}
	$form['generated_appointment_list'] = array(
						    '#markup' => generate_appointment_html($student_list,$term_id,$form_state['complete form']['#action'],$form_state['values']['aid_type_select_list'])
						    );
      }
    }
    else{
      drupal_set_message("You must select students and choose 'Stipend > 0' to Generate the TA/GA form",'error');
    }
  }
  
  //return system_settings_form($form); this puts the save config button on the bottom.
  return $form;
}

function get_aid_type_list($form, &$form_state){
  return $form['term_select_field_set']['select_aid_type'];
}

function create_student_choices($form, $form_state){
  return $form['term_select_field_set']['select_aid_type']['select_ta_ga_students'];
}

function alter_term_choices($form,$form_state){
  return $form['term_select_field_set'];
}

//function get_position_num($account){
function get_position_num($account,$aid_nid){
  $load_aid_type = entity_load('node',array($aid_nid));
  //get the aid title for the wierd departments
  $aid_title = strtolower(trim($load_aid_type[$aid_nid]->title));
  switch ($account){
  case '211105': 
    $position = 'GT9960'; //Bio
    break;
  case '211310':
    $position = 'GT9950'; //Chem
    break;
  case '211125':
    $position = 'GT9940'; //EES
    break;
  case '211115':
    //English
    if($aid_title=='ta'){
      $position = 'GT9930';
    }
    elseif($aid_title=='senior ta'){
      $position = 'GT9940';
    }
    else{
      $position = '';
    }
    break;
  case '211135':
    $position = 'GT9910'; //History
    break;
  case '211145':
    //Math
    if($aid_title == 'grader' || $aid_title == 'graders'){
      $position = 'GT9890';
    }
    else{
      $position = 'GT9900';
    }
    break;
  case '211340':
    $position = 'GT9880';//Physics
    break;
  case '211130':
    $position = 'GT9870';//PoliSci
    break;
  case '211165':
    //Psych
    if($aid_title == 'ta'){
      $position = 'GT9850';
    }
    else{
      $position = 'GT9860';
    }
    break;
  case '211175':
    $position = 'GT9840'; //Socanthro
    break;
  case '211189':
    $position = 'GT9820'; //EI (EPD?)
    break;
  default:
    $position = '';
  }

      return $position;
}

function generate_appointment_html($stud_list,$term_id,$form_url,$aid_nid){
  drupal_set_message('Any Messages here will not appear when printing.','status');
  drupal_set_message('Use <a href="'.$form_url.'"/>this link</a> to go back to the form selection page instead of refreshing the page.','status');
  $accntend = 61510;
  $dept = get_dept_title_from_url($form_url);
  $list_html = '';

  $term_load = entity_load('taxonomy_term',array($term_id));
  
  $term_ent_vals = array_values($term_load);
  $term_ent = $term_ent_vals[0];
  
  $term_code = $term_ent->field_banner_term_code['und'][0]['value'];

  $entities = entity_load('node',$stud_list);

  $total_stipend = 0;
  $total_rate = 0;
  $table_html = '';
  $error = FALSE; //setup a variable to track if there were errors while generating this table. assume no errors unless there is one

  $first_entry = array_pop(array_reverse($entities)); //set the account number
  $first_nid = $first_entry->nid;
  $account = $first_entry->field_account_number['und'][0]['value'];
  $position = get_position_num($account,$aid_nid);
  $name = $first_entry->field_student_last_name['und'][0]['value'].', '.$first_entry->field_student_first_name['und'][0]['value'];
  $first_effort = !empty($first_entry->field_effort['und'][0]['value']) ? $first_entry->field_effort['und'][0]['value'] : 0 ;
  $first_periods = !empty($first_entry->field_pay_periods['und'][0]['value']) ? $first_entry->field_pay_periods['und'][0]['value'] : 0;
  $first_start = !empty($first_entry->field_aid_date['und'][0]['value']) ? $first_entry->field_aid_date['und'][0]['value'] : 0;
  $first_end = !empty($first_entry->field_aid_date['und'][0]['value2']) ? $first_entry->field_aid_date['und'][0]['value2'] : 0;

  $lin_list = array();
  $first_error = '';

  //check to make sure each of the items for the first entry in the list is filled in.
  if($first_effort != 50){
    $error = TRUE;
    $first_error .= 'must be 50% Effort, ';
  }
  if($first_periods == 0){
    $error = TRUE;
    $first_error .= 'is missing Pay Periods, ';
  }
  if($first_start == 0){
    $error = TRUE;
    $first_error .= 'is missing Start Date, ';
  }
  if($first_end == 0){
    $error = TRUE;
    $first_error .= 'is missing End Date, ';
  }
  //only need to set start and end date if there is no errors, if there are no errors you can set both start and end date
  if(!$error){
      $start = new DateTime($first_start);
      $start_date = $start->format('m-d-Y');
      $end = new DateTime($first_end);
      $end_date = $end->format('m-d-Y');      
  }
  if($error){
    drupal_set_message('The first Entry in the list, <a href="/node/'.$first_nid.'">'.$name.'</a>, '.$first_error.'this will create an error for each entry in the list','error');
  }

  foreach($entities as $curentry){
    $cur_error = FALSE; //variable to tell if there is an error for the current entry for displaying an error message.
    $cur_message = '';
    $cur_lin = $curentry->field_lin['und'][0]['value'];
    $name = $curentry->field_student_last_name['und'][0]['value'].', '.$curentry->field_student_first_name['und'][0]['value'];
    if(isset($lin_list[$cur_lin])){
      //check to make sure that a single persion is not in the list more than once.
      $error = TRUE;
      drupal_set_message('ERROR: <a href="/node/'.$curentry->nid.'">'.$name.'</a> Is in this list more than once. A student can only be in this form once','error');
    }
    else{
      $lin_list[$cur_lin] = 1;
      if($curentry->field_account_number['und'][0]['value'] != $account){
	//Make sure the account number is the same
	$error = TRUE;
	$cur_error = TRUE;
	$cur_message .= ' has a different account #,';
      }
      $effort = !empty($curentry->field_effort['und'][0]['value']) ? $curentry->field_effort['und'][0]['value'] : '0' ;
      if($effort != 50){
	//Make sure the % effort is 50
	$error = TRUE;
	$cur_error = TRUE;
	$cur_message .= ' must be 50% Effort,';
      }
      $periods = !empty($curentry->field_pay_periods['und'][0]['value']) ? $curentry->field_pay_periods['und'][0]['value'] : 'error';
      if($periods != $first_periods){
	//Make sure Pay Periods is the same
	$error = TRUE;
	$cur_error = TRUE;
	$cur_message .= ' has a different number Pay Periods,';
      }
      $cur_start = !empty($curentry->field_aid_date['und'][0]['value']) ? $curentry->field_aid_date['und'][0]['value'] : 'error';
      if($cur_start != $first_start){
	//Make sure Start Date is the same
	$error = TRUE;
	$cur_error = TRUE;
	$cur_message .= ' has a different Start Date,';
      }
      $cur_end = !empty($curentry->field_aid_date['und'][0]['value2']) ? $curentry->field_aid_date['und'][0]['value2'] : 'error';
      if($cur_end != $first_end){
	//Make sure Start Date is the same
	$error = TRUE;
	$cur_error = TRUE;
	$cur_message .= ' has a different End Date,';
      }

      if($cur_error){
	//present the error message for this entry is there is one
	drupal_set_message('ERROR: <a href="/node/'.$curentry->nid.'">'.$name.'</a> '.rtrim($cur_message,',').'.','error');
      }
      if(!$error){
	//now I can generate this row.
	$id =  $curentry->field_lin['und'][0]['value'];
	$phone =  $curentry->field_phone['und'][0]['value'];
	$stipend = $curentry->field_stipend['und'][0]['value'];
	$rate =  $stipend/$first_periods;      
	//Totals
	$total_stipend = $total_stipend + $stipend;
	$total_rate = $total_rate + $rate;
	//create the row
	$thisrow = '<tr><td>'.$name.'</td><td>'.$id.'</td><td>'.$phone.'</td><td>'.$start_date.'</td><td>'
	  .$end_date.'</td><td>'.$first_effort.'</td><td>'.$first_periods.'</td><td>$'
	  .number_format($rate,2,'.',',').'</td><td>$'.number_format($stipend,2,'.',',').'</td></tr>';
      
	//Add the row to the list
	$table_html = $table_html.$thisrow;
      }//end of generating a row
    }
  }//end of the foreach entry/entity selected

  if($error){
    return "<h1>Some of the entries you've selected have errors, please see the list above.</h1><h1>Fix These errors or deselect these entries to generate this form</h1><p>NOTE: Errors indicating differences are compared to the first entry in the list you've selected.</p>";
  }    
  else{
  $list_top_html = '<div class="appointment-list-page-wrapper">
                    <div class="appointment-list-inner-wrapper">
                    <div class="appointment-list-header">
                    <h1 class="appointment-list-head-text">TA/GA Appointment List</h1>
                    <div class="header-line-1 clearfix"><div class="term-space"><p>Term: <span class="term-id">'.$term_code.'</span></p></div>
                    <div class="account-space"><p>'.$account.'-'.$accntend.'</p></div></div>
                    <div class="header-line-2 clearfix"><div class="department-space"><p>Department:  <span class="department-name">'.$dept.'</span></p></div>
                    <div class="account-name"><p>Account</p></div></div></div>';

  $list_html = $list_html.$list_top_html;

  $table_header = '<table class="appointment-table"><tr class="table-header">
                           <th>Employee Name</th>
                           <th>Lehigh ID</th>
                           <th>Phone Ext.</th>
                           <th>Start Date</th>
                           <th>End Date</th>
                           <th>Percent Effort</th>
                           <th>Pay Periods</th>
                           <th>Periodic Rate</th>
                           <th>Total Stipend</th>                       
               </tr>';
  
  $list_html = $list_html.$table_header;
  $list_html = $list_html.$table_html;

  //Don't forget to style this final row differently
  $table_footer = '<tr class="last-row"><td></td><td></td><td></td><td></td><td></td><td></td>
                   <td class="final-totals"><strong>Totals:</strong></td><td class="final-totals"> $'.number_format($total_rate,2,'.',',')
                   .'</td><td class="final-totals"> $'.number_format($total_stipend,2,'.',',').'</td></tr></table>';

  $list_html = $list_html.$table_footer;

  $below_table = '<div class="sub-table">
                  <div class="sub-table-1 clearfix"><p>*Please use full legal name</p></div>
                  <div class="sub-table-2 clearfix"><p>For internal use only</p></div>
                  <div class="sub-table-3 clearfix"><p id="tkl">TKL</p><div class="internal-use-line"></div>
                                                    <div class="accnt-exec-line"><p>Account Executive</p></div>
                                                    <div class="date-line"><p>Date</p></div></div>
                  <div class="sub-table-4 clearfix"><p id="ddu">DDU</p><div class="internal-use-line"></div></div>
                  <div class="sub-table-5 clearfix"><p id="position-num">Position #</p><div class="internal-use-line"><p> '.$position.'</p></div></div>
                  <div class="sub-table-6 clearfix"><div class="no-status-change"><p>This form may not be used to report</p>
                                                                                  <p>change in existing status</p></div>
                                                    <div class="initials-table-div">
                                                    <table class="initials-table"><tr><th class="initials-initials">Initials</th>
                                                               <th class="initials-date">Date</th>
                                                               <th class="initials-rout">Routing</th></tr>
                                                    <tr><td></td><td></td><td>College Dean</td></tr>
                                                    <tr><td></td><td></td><td>Graduate Dean</td></tr>
                                                    <tr><td></td><td></td><td>Vice President</td></tr>
                                                    </table></div></div>
                 <div class="sub-table-last"><p>After obtaining signatures, return form to payroll office.</p></div></div>';

  $list_html = $list_html.$below_table;

  $list_html = $list_html.'</div></div>';


    return $list_html;
  }
}

function tuition_tool_forms_ta_ga_submit($form, &$form_state){
  $form_state['rebuild'] = TRUE;
}

function tuition_tool_forms_payroll_assignment($form, &$form_state){
  $form_state['rebuild'] = FALSE;  

  $max_forms = 100; //This is a failsafe to make sure we aren't generating too many forms or making any single form too big.

  $entities = entity_load('node',$form_state['values']['choose_students_table']);
  if(count($entities) > 0){
    $department = get_dept_title_from_url($form_state['complete form']['#action']); //department name for dispaly
    //get the short or 'machine' version of the department name
    $dept_array = explode('/',$form_state['complete form']['#action']);
    $dept_forms = explode('_forms',$dept_array[4]);
    $dept_short = $dept_forms[0];

    //get the aid type, but you only need to do it once.
    $aid_nid = $form_state['values']['aid_type_select_list'];
    $aid_ent = entity_load('node',array($aid_nid));
    $aid_type = $aid_ent[$aid_nid]->title;
    $is_fellowship = strpos(strtolower($aid_type),'fellowship');
    //get the term code for the file name
    $load_term = entity_load('taxonomy_term',array($form_state['values']['select_term']));
    $term_obj = $load_term[$form_state['values']['select_term']];
    $term_code = $term_obj->field_banner_term_code['und'][0]['value'];    
    $term_title = $term_obj->name;

    $lin_list = array();//the main data list.
    $error_list = array(); //a place to store errors
    
    foreach($entities as $nid => $curentry){
      $id =  $curentry->field_lin['und'][0]['value'];
      if(isset($error_list[$id])){
	//if the id has already created an error then skip over all of this
	continue;
      }

      $account = $curentry->field_account_number['und'][0]['value'];
      $full_name = $curentry->field_student_last_name['und'][0]['value'].', '.$curentry->field_student_first_name['und'][0]['value'];
      //MAKE SURE the important fields are all filled in.
      if(empty($curentry->field_aid_date['und'][0]['value']) || empty($curentry->field_aid_date['und'][0]['value2']) || empty($curentry->field_pay_periods['und'][0]['value']) || empty($curentry->field_stipend['und'][0]['value'])){
	drupal_set_message("Stipend, Account, Start Date, End Date, and Pay Periods, ALL must be filled in for each entry. Skipping all entries for ".$full_name,'error');
	$error_list[$id] = 1;
	if(isset($lin_list[$id])){
	  unset($lin_list[$id]);
	}
      }
      else{															    
	if(empty($curentry->field_effort['und'][0]['value'])){
	    if($is_fellowship === FALSE){
	      drupal_set_message("Effort must be filled in for each entry. Skipping all entries for ".$full_name,'error');
	      $error_list[$id] = 1;
	      if(isset($lin_list[$id])){
		unset($lin_list[$id]);
	      }
	      continue;
	    }
	    else{
	      $effort = 0;
	    }
	  }
	  else{
	    $effort = $curentry->field_effort['und'][0]['value'];
	    //check that effort is less than 50
	    if($effort > 50){
	      //This is an error unless it's a summer RA
	      if(!(strtolower(trim($aid_type)) == 'ra' && !(strpos(strtolower($term_title),'summer') === FALSE))){
		drupal_set_message('Effort cannot be greater than %50. Error on <a href="/node/'.$nid.'">node/'.$nid.'</a>'.' Skipping all entries with LIN: '.$id,'error');
		$error_list[$id] = 1;
		if(isset($lin_list[$id])){
		  unset($lin_list[$id]);
		}
		continue;
	      }
	    }
	  }

	$start_date = new DateTime($curentry->field_aid_date['und'][0]['value']);
	$end_date = new DateTime($curentry->field_aid_date['und'][0]['value2']);
	$periods = $curentry->field_pay_periods['und'][0]['value'];

	if(isset($lin_list[$id])){ //if the LIN (id) is already in the list
	  //CHECK ALL START_DATE, END_DATE, EFFORT, PERIODS
	  $first_nid = $lin_list[$id]['header']['first_nid'];
	  //PAY PERIODS
	  if($periods != $lin_list[$id]['header']['periods']){
	    drupal_set_message('Error: PAY PERIODS mismatch between <a href="/node/'.$nid.'">node/'.$nid.'</a> and <a href="/node/'.$first_nid.'">node/'.$first_nid.'</a>. '.$full_name.' will not be in the PDF. <strong>Change the Pay Periods OR print out the forms separately.</strong>','error');
	    unset($lin_list[$id]);
	    $error_list[$id] = 1;
	    continue;
	  }
	  //EFFORT CHECK
	  elseif($effort != $lin_list[$id]['header']['effort']){
	    drupal_set_message('Error: % EFFORT mismatch between <a href="/node/'.$nid.'">node/'.$nid.'</a> and <a href="/node/'.$first_nid.'">node/'.$first_nid.'</a>. '.$full_name.' will not be in the PDF. <strong>Change the %Effort OR print out the forms separately.</strong>','error');
	    unset($lin_list[$id]);
	    $error_list[$id] = 1;
	    continue;
	  }
	  //ACCOUNT NUMBER COLLISION CHECK
	  elseif(isset($lin_list[$id]['accounts'][$account])){
	    drupal_set_message('ERROR: Account number '.$account.' is already in the list for '.$full_name.'. It cannot be in more than once. Check <a href="/node/'.$nid.'">node/'.$nid.'</a> to change this.','error');
	    unset($lin_list[$id]);
	    $error_list[$id] = 1;
	    continue;
	  }
	  //ACCOUNT NUMBER LIMIT CHECK
	  elseif(count($lin_list[$id]['accounts']) == 5){
	    //There are already 5 in the list and they are trying to add another. Throw an error
	    drupal_set_message('Error: MORE THAN 5 ACCOUNTS. 2 offending nodes: <a href="/node/'.$nid.'">node/'.$nid.'</a> and <a href="/node/'.$first_nid.'">node/'.$first_nid.'</a>. '.$full_name.' will not be in the PDF. Remove some stipend/account entries or print out the forms separately.','error');
	    unset($lin_list[$id]);
	    $error_list[$id] = 1;
	    continue;
	  }
	  else{
	    //Add the account, stipend, start and end date to the list
	    $lin_list[$id]['accounts'][$account] = array(
					       'stipend' => $curentry->field_stipend['und'][0]['value'],
					       'start' => $start_date,
					       'end' => $end_date,
						       );

	    $lin_list[$id]['header']['total'] += $curentry->field_stipend['und'][0]['value']; //increase the value for the total
	  }
	}
	else{	//create a new entry in the list of lins since it's not in the error list or not already in the list
	  $lin_list[$id] = array();

	  //create the header info array
	  $lin_list[$id]['header'] = array(
					   'last' => $curentry->field_student_last_name['und'][0]['value'],
					   'first' => $curentry->field_student_first_name['und'][0]['value'],
					   'dept' => $department,
					   'location' => $curentry->field_check_location['und'][0]['value'],
					   'contact' => !empty($curentry->field_contact['und'][0]['value']) ? $curentry->field_contact['und'][0]['value'] : '',
					   'phone' => $curentry->field_phone['und'][0]['value'],
					   'aid_type' => $aid_type,
					   'periods' => $periods,
					   'effort' => $effort,
					   'total' => $curentry->field_stipend['und'][0]['value'],
					   'first_nid' => $nid,
					   );
	  //create the accounts part of the list
	  $lin_list[$id]['accounts'] = array();
	  $lin_list[$id]['accounts'][$account] = array(
					       'stipend' => $curentry->field_stipend['und'][0]['value'],
					       'start' => $start_date,
					       'end' => $end_date,
						       );
	}
	//array of information completed
      } 
    }     
    if(count($lin_list) == 0){
      drupal_set_message("All of the students selected caused errors. Please fix the errors listed above to generate this form.",'error');
    }
    elseif(count($lin_list) > $max_forms){
      drupal_set_message("WHOA! That's too many entries, over ".$max_forms." for one form. email MaryAnn and Devan about this error",'error');
    }
    else{//it's good to start generating the forms and the final form.
      $pdf_list = array();
      foreach($lin_list as $lin => $form_values){
	$single_pdf = generate_payroll_single_pdf($lin,$form_values['header'],$form_values['accounts']);
	if($single_pdf == 'ERROR-GENERATING-TEMP-FDF' || !file_exists($single_pdf)){
	  drupal_set_message('Error Generating the pdf for '.$form_values['header']['first'].' '.$form_values['header']['last'],'error');
	  continue;
	}
	else{
	  $pdf_list[] = $single_pdf;
	}
      }
      
      $final_pdf = drupal_get_path('module','tuition_tool_forms').'/../../files/private/'.$dept_short.'/forms/'.str_replace(" ","",$department).'_'.str_replace(" ","",$aid_type).'_'.$term_code.'-PAF-'.date("mdGis").'.pdf';
      
      present_filled_pdf($final_pdf,$pdf_list);
      //maybe delete the filled pdf, or just send a success or error message here at the end.
    }
  }
  else{
    drupal_set_message("No students selected from the list, please select students whose data can go into the Payroll Assignment Form",'error');
  }
  
}

function generate_payroll_single_pdf($lin,$head,$accnts){
  //don't forget to convert the DateTime objects to readable format.
  //FIRST construct the header info before iteration through the account numbers
  
  $fdf_data = '<</T(Last Name)/V('.$head['last'].')>>'.
              '<</T(First Name)/V('.$head['first'].')>>'.
              '<</T(Department where Payroll records are kept)/V('.$head['dept'].')>>'.
              '<</T(LIN/ID Number)/V('.$lin.')>>'.
              '<</T(Check Dist Location)/V('.$head['location'].')>>'.
              '<</T(Department Contact Person)/V('.$head['contact'].')>>'.
              '<</T(Ext)/V('.$head['phone'].')>>'.
              '<</T(Position Title)/V('.$head['aid_type'].')>>'.
              '<</T(Salary Per Pay)/V($'.number_format($head['total']/$head['periods'],2,'.',',').')>>'.
              '<</T(Pay ID)/V('.$head['periods'].')>>'.
              '<</T(FTE)/V('.$head['effort'].'%)>>'.
    '<</T(Annual Salary)/V($'.number_format($head['total'],2,'.',',').')>>';
  //Now fill in the rest of the data with a foreach loop
  $count = 1;
  foreach($accnts as $account => $stipinf){
    $start = $stipinf['start']->format('m-d-Y');
    $end = $stipinf['end']->format('m-d-Y');
    $stipend = $stipinf['stipend'];
    $i = strval($count);
    $fdf_data .= '<</T(Index '.$i.')/V('.$account.')>>'.
                 '<</T(Index Distribution '.$i.')/V('.number_format(100*($stipend/$head['total']),2,'.',',').'%)>>'.
                 '<</T(Start Date '.$i.')/V('.$start.')>>'.
                 '<</T(End Date '.$i.')/V('.$end.')>>'.
      '<</T(Dollars '.$i.')/V($'.number_format($stipend,2,'.',',').')>>';

    $count += 1;
  }
  $input_form = drupal_get_path('module','tuition_tool_forms').'/fillable_forms/Payroll_Assignment.pdf';
  $output_path = drupal_get_path('module','tuition_tool_forms').'/../../files/private/tuitiontoolforms/';//tuitiontoolforms
  //time to add to filename so it is unique
  $now = date("YmdGis");
  //sanatize first and last names of non-alpha-numeric characters since it's being saved as a file.
  $san_last = preg_replace("/[^A-Za-z0-9]/",'',$head['last']);
  $san_first = preg_replace("/[^A-Za-z0-9]/",'',$head['first']);
  //additionall add aid type, with white spaces stipped out:
  //$strip_aid = preg_replace(' ','',$head['aid_type']);
  $outpdf = $output_path.$san_last.'_'.$san_first.'-PAF-'.$now.'.pdf';
  $temp_fdf = gen_temp_fdf($fdf_data);

  if(file_exists($temp_fdf)){
    exec("pdftk ".$input_form." fill_form ".$temp_fdf." output ".$outpdf." flatten");
    unlink($temp_fdf);
    return $outpdf;
  }
  else{
    //if there's ever a problem with generating the file I could make a few more attempts to generate the file here.
    return 'ERROR-GENERATING-TEMP-FDF';
  }
}

function tuition_tool_forms_tuition_award($form, &$form_state){
  $form_state['rebuild'] = FALSE;
  
  $max_forms = 100; //This is a failsafe to make sure we aren't generating too many forms or making any single form too big.

  if($form_state['values']['tuition_or_stipend'] == 0){
    drupal_set_message("You must choose 'Tuition > 0' to generate this form",'error');
  }
  else{
    $entities = entity_load('node',$form_state['values']['choose_students_table']);  
    if(count($entities) > 0){
      //set some header values that won't change between students
      $department = get_dept_title_from_url($form_state['complete form']['#action']);// long department name for display
      //get the short or 'machine' name of the department
      $dept_array = explode('/',$form_state['complete form']['#action']);
      $dept_forms = explode('_forms',$dept_array[4]);
      $dept_short = $dept_forms[0];  
      //get the aid type, but you only need to do it once.
      $aid_nid = $form_state['values']['aid_type_select_list'];
      $aid_ent = entity_load('node',array($aid_nid));
      $aid_type = $aid_ent[$aid_nid]->title;
      //get the term code for the file name
      $load_term = entity_load('taxonomy_term',array($form_state['values']['select_term']));
      $term_obj = $load_term[$form_state['values']['select_term']];
      $term_code = $term_obj->field_banner_term_code['und'][0]['value'];
      //setup the date
      $date = date('m-d-Y');
      //lists for storing the entries and tracking errors
      $lin_list = array();//the main data list.
      $error_list = array(); //a place to store errors
      foreach($entities as $nid => $curentry){
	$id =  $curentry->field_lin['und'][0]['value'];
	$account = $curentry->field_account_number['und'][0]['value'];
	$full_name = $curentry->field_student_last_name['und'][0]['value'].', '.$curentry->field_student_first_name['und'][0]['value'];

	if(!(isset($curentry->field_credits['und'][0]['value']))){
	  //for some reason there is no credits, this is an error
	  drupal_set_message('ERROR: No Credits entered for '.$full_name.' at <a href="/node/'.$nid.'">node/'.$nid.'</a>. This person will not be in the final pdf, please change the erroneous node listed.','error');
	    unset($lin_list[$id]);
	    $error_list[$id] = 1;
	    continue;
	}
	else{
	  //MAKE SURE the important fields are all filled in.
	  if(isset($lin_list[$id]) && !(isset($error_list[$id]))){ //if the LIN (id) is already in the list and not in the error list
	    if(isset($lin_list[$id]['accounts'][$account])){
	      drupal_set_message('ERROR: Account number '.$account.' is already in the list for '.$full_name.'. It cannot be in more than once. Check <a href="/node/'.$nid.'">node/'.$nid.'</a> to change this.','error');
	      unset($lin_list[$id]);
	      $error_list[$id] = 1;
	      continue;
	    }
	    elseif(count($lin_list[$id]['accounts']) == 3){
	      //this is an error there can only be 3 accounts entered
	      drupal_set_message('There can only be 3 account/credit hours entered per student per position for this form. see <a href="/node/'.$nid.'">node/'.$nid.'</a> to fix this','error');
	      unset($lin_list[$id]);
	      $error_list[$id] = 1;
	      continue;
	    }
	    else{
	      $lin_list[$id]['accounts'][$account] = $curentry->field_credits['und'][0]['value'];
	      $lin_list[$id]['header']['total'] += $curentry->field_credits['und'][0]['value']; //increase the value for the total
	    }
	  }
	  else{	//create a new entry in the list of lins since it's not in the error list or not already in the list
	    $lin_list[$id] = array();
	    //get the student's degree.  program and degree are essentially the same thing.
	    if(!empty($curentry->field_student_degree['und'][0]['value'])){
	      $degree = $curentry->field_student_degree['und'][0]['value'];
	    }
	    elseif(!empty($curentry->field_student_program['und'][0]['value'])){
	      $degree = $curentry->field_student_program['und'][0]['value'];
	    }
	    else{
	      $degree = '';
	    }
	    //create the header info array
	    $lin_list[$id]['header'] = array(
					     'term' => $term_code,
					     'last' => $curentry->field_student_last_name['und'][0]['value'],
					     'first' => $curentry->field_student_first_name['und'][0]['value'],
					     'date' => $date,
					     'dept' => $department,
					     'degree' => $degree,
					     'aid_type' => $aid_type,
					     'total' => $curentry->field_credits['und'][0]['value'],
					     );
	    //create the accounts part of the list
	    $lin_list[$id]['accounts'] = array();
	    $lin_list[$id]['accounts'][$account] = $curentry->field_credits['und'][0]['value'];
	  }
	}//else for if no credits are set.
      }//foreach $entities

      //time to generate some forms.
      if(count($lin_list) == 0){
	drupal_set_message("All of the students selected caused errors. Please fix the errors listed above to generate this form.",'error');
      }
      elseif(count($lin_list) > $max_forms){
	drupal_set_message("WHOA! That's too many entries, over ".$max_forms.", for one form. email MaryAnn and Devan about this error",'error');
      }
      else{//it's good to start generating the forms and the final form.
	$pdf_list = array();
	foreach($lin_list as $lin => $form_values){
	  $single_pdf = generate_tuition_single_pdf($lin,$form_values['header'],$form_values['accounts']);
	  if($single_pdf == 'ERROR-GENERATING-TEMP-FDF' || !file_exists($single_pdf)){
	    drupal_set_message('Error Generating the pdf for '.$form_values['header']['first'].' '.$form_values['header']['last'],'error');
	    continue;
	  }
	  else{
	  $pdf_list[] = $single_pdf;
	  }
	}
	
	$final_pdf = drupal_get_path('module','tuition_tool_forms').'/../../files/private/'.$dept_short.'/forms/'.str_replace(" ","",$department).'_'.str_replace(" ","",$aid_type).'_'.$term_code.'-UTAF-'.date("mdGis").'.pdf';
      
	present_filled_pdf($final_pdf,$pdf_list);
	//maybe delete the filled pdf, or just send a success or error message here at the end.
      }
    }//if count(entities) > 0
    else{
      drupal_set_message("No students selected from the list, please select students whose data can go into the Tuition Award Form",'error');
    }
  }//end of else of 'tuition_or_stipend' == 0

}

function generate_tuition_single_pdf($lin,$head,$accnts){
  //don't forget to convert the DateTime objects to readable format.
  //FIRST construct the header info before iteration through the account numbers
  
  $fdf_data = '<</T(For Semester)/V('.$head['term'].')>>'.
              '<</T(Last Name)/V('.$head['last'].')>>'.
              '<</T(First Name)/V('.$head['first'].')>>'.
              '<</T(LIN)/V('.$lin.')>>'.
              '<</T(Date)/V('.$head['date'].')>>'.
              '<</T(Department)/V('.$head['dept'].')>>'.
              '<</T(Degree)/V('.$head['degree'].')>>'.
              '<</T(Position)/V('.$head['aid_type'].')>>'.
              '<</T(# of credits paid by UTA)/V('.number_format($head['total'],2,'.',',').')>>';
  //Now fill in the rest of the data with a foreach loop
  $count = 1;
  foreach($accnts as $account => $credits){
    $i = strval($count);
    $fdf_data .= '<</T(Credit Hours '.$i.')/V('.number_format($credits,2,'.',',').')>>'.
                 '<</T(Index '.$i.')/V('.$account.')>>'.
                 '<</T(Account # '.$i.')/V(73571)>>';
    $count += 1;
  }
  $input_form = drupal_get_path('module','tuition_tool_forms').'/fillable_forms/Tuition_Award.pdf';
  $output_path = drupal_get_path('module','tuition_tool_forms').'/../../files/private/tuitiontoolforms/';
  //time to add to filename so it is unique
  $now = date("YmdGis");
  //sanatize first and last names of non-alpha-numeric characters since it's being saved as a file.
  $san_last = preg_replace("/[^A-Za-z0-9]/",'',$head['last']);
  $san_first = preg_replace("/[^A-Za-z0-9]/",'',$head['first']);
  //additionall add aid type, with white spaces stipped out:
  //$strip_aid = preg_replace(' ','',$head['aid_type']);
  $outpdf = $output_path.$san_last.'_'.$san_first.'-UTAF-'.$now.'.pdf';
  $temp_fdf = gen_temp_fdf($fdf_data);

  if(file_exists($temp_fdf)){
    exec("pdftk ".$input_form." fill_form ".$temp_fdf." output ".$outpdf." flatten");
    unlink($temp_fdf);
    return $outpdf;
  }
  else{
    //if there's ever a problem with generating the file I could make a few more attempts to generate the file here.
    return 'ERROR-GENERATING-TEMP-FDF';
  }
}

function gen_temp_fdf($data){

  $fdf_head = '%FDF-1.2
1 0 obj<</FDF << /Fields [';

  $fdf_foot =  "] >> >>
endobj
trailer
<</Root 1 0 R>>
%%EOF";
 
  $rand_pre = strval(rand(1,1000)); //a random prefix for the file so that we don't have any file collision

  $content = $fdf_head.$data.$fdf_foot;
  
  $temp_name = tempnam('/tmp',$rand_pre);
  $temp_file = fopen($temp_name, 'w');
  fwrite($temp_file,$content);
  fclose($temp_file);
  return $temp_name;
}

function present_filled_pdf($file_name,$pdf_list){
  //I can use this to present both types of pdf's

  $command = "pdftk ";

  foreach($pdf_list as $pdf){
    if(file_exists($pdf)){
      $command .= $pdf." ";
    }
    else{
      drupal_set_message("File ".end(explode('/',$pdf))." Could not be found and will not be added to the final PDF. email dlb213@lehigh.edu about this error.",'error');
    }
  }

  $command .= "cat output ".$file_name;
  
  exec($command);
  
  if(file_exists($file_name)){
    foreach($pdf_list as $pdf){
      //remove the other pdfs if the final pdf has been made
      if(file_exists($pdf)){
	unlink($pdf);
      }
    }

    $just_name = end(explode('/',$file_name));
    $file_url = '/system/files'.end(explode('/private',$file_name));

    drupal_set_message('SUCCESS! View and Download your file: <a href="'.$file_url.'">'.$just_name.'</a>.','status');        
  }
  else{
    drupal_set_message("Error generating file",'error');
  }
}
